"""Lake integration for rules_lean.

`lake_workspace` is a repository rule that materializes a Lake workspace
(lakefile + lake-manifest.json) into a Bazel-managed external repo,
downloads the matching Lean toolchain, runs `lake exe cache get` to pull
prebuilt mathlib oleans from upstream Reservoir, and exposes:

  - `@<name>//:lean_toolchain` — register via `register_toolchains(...)`.
  - `@<name>//:Mathlib`        — consolidated `lean_prebuilt_library`
                                 containing oleans for every Lake package
                                 in the resolved workspace.

Use via the module extension:

    lake = use_extension("@rules_lean//lean:lake.bzl", "lake")
    lake.workspace(
        name = "lake_deps",
        lean_toolchain = "//:lean-toolchain",
        lakefile = "//:lakefile.lean",
        lake_manifest = "//:lake-manifest.json",
    )
    use_repo(lake, "lake_deps")
    register_toolchains("@lake_deps//:lean_toolchain")

Hermeticity:
  - The Lean toolchain is downloaded with a known sha256 (see
    private/known_lean_versions.bzl) when the version is pinned there.
    Unpinned versions download unverified (warning emitted).
  - Lake dep revs are pinned by the user's committed lake-manifest.json.
  - Mathlib oleans are content-addressed by mathlib's commit hash in the
    upstream Reservoir cache; integrity is verified by Lake.

Constraints on the lakefile passed in:
  - Should be a *deps-only* lakefile (the rule creates a placeholder
    package source). Build directives (`lean_lib`, `lean_exe`) for the
    user's own code don't belong here — those live in Bazel BUILD files
    via the `lean_test` / `lean_emit` rules.
"""

load("//lean/private:known_lean_versions.bzl", "KNOWN_LEAN_VERSIONS", "PLATFORM_ASSETS")

LEAN_RELEASE_BASE = "https://github.com/leanprover/lean4/releases/download"

def _detect_platform(rctx):
    os_name = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if "mac" in os_name or "darwin" in os_name:
        if arch in ("aarch64", "arm64"):
            return "darwin_aarch64"
        return "darwin_x86_64"
    if "linux" in os_name:
        if arch in ("aarch64", "arm64"):
            return "linux_aarch64"
        return "linux_x86_64"
    fail("rules_lean: unsupported platform os=%s arch=%s" % (os_name, arch))

def _parse_lean_toolchain(content):
    """Parse a `lean-toolchain` file. Returns the version tag (with leading 'v')."""
    line = content.strip().split("\n")[0].strip()
    if ":" not in line:
        fail("lean-toolchain: expected 'leanprover/lean4:vX.Y.Z', got %r" % line)
    _, version = line.split(":", 1)
    version = version.strip()
    if not version.startswith("v"):
        version = "v" + version
    return version

def _download_lean(rctx, version, platform):
    asset_template = PLATFORM_ASSETS.get(platform)
    if not asset_template:
        fail("rules_lean: no asset template for platform %s" % platform)
    asset = asset_template.format(v = version.lstrip("v"))
    sha = KNOWN_LEAN_VERSIONS.get(version, {}).get(platform, "")
    url = "{base}/{ver}/{asset}".format(base = LEAN_RELEASE_BASE, ver = version, asset = asset)
    if not sha:
        # buildifier: disable=print
        print("rules_lean: WARNING — no pinned sha256 for Lean %s on %s; downloading unverified. " %
              (version, platform) +
              "Add an entry to known_lean_versions.bzl for hermetic builds.")
    rctx.download_and_extract(
        url = url,
        sha256 = sha,
        output = "lean_toolchain",
        stripPrefix = asset.removesuffix(".zip"),
    )

def _stage_lake_workspace(rctx):
    """Stage lakefile + manifest + lean-toolchain + placeholder package source into lake_ws/."""
    # Use the user's actual filenames so Lake recognizes them.
    lakefile_basename = rctx.path(rctx.attr.lakefile).basename
    manifest_basename = rctx.path(rctx.attr.lake_manifest).basename

    rctx.symlink(rctx.attr.lakefile, "lake_ws/" + lakefile_basename)
    rctx.symlink(rctx.attr.lake_manifest, "lake_ws/" + manifest_basename)
    rctx.symlink(rctx.attr.lean_toolchain, "lake_ws/lean-toolchain")

    # Lake refuses to operate without at least one source file matching the
    # package. The placeholder is a minimal valid Lean module.
    rctx.file("lake_ws/_RulesLeanPlaceholder.lean", "-- generated by rules_lean\n")

def _run_lake(rctx, args, timeout, env):
    lake_bin = str(rctx.path("lean_toolchain/bin/lake"))
    result = rctx.execute(
        [lake_bin] + args,
        working_directory = "lake_ws",
        environment = env,
        timeout = timeout,
        quiet = False,
    )
    return result

def _lake_env(rctx):
    bin_dir = str(rctx.path("lean_toolchain/bin"))
    return {
        "PATH": "{bin}:{rest}".format(bin = bin_dir, rest = rctx.os.environ.get("PATH", "/usr/bin:/bin")),
        "LEAN_HOME": str(rctx.path("lean_toolchain")),
        "ELAN_TOOLCHAINS": "",  # discourage elan from intervening
    }

def _list_lake_packages(rctx):
    """Return list of package directory names under lake_ws/.lake/packages/."""
    pkgs_dir = rctx.path("lake_ws/.lake/packages")
    if not pkgs_dir.exists:
        return []
    result = rctx.execute(["ls", "-1", str(pkgs_dir)])
    if result.return_code != 0:
        return []
    return [line for line in result.stdout.strip().split("\n") if line]

def _consolidate_oleans(rctx, packages):
    """Merge .lake/packages/*/.lake/build/lib/lean/ into lib/. Returns True if non-empty."""
    rctx.execute(["rm", "-rf", "lib"])
    rctx.execute(["mkdir", "-p", "lib"])
    any_merged = False
    for pkg in packages:
        src = rctx.path("lake_ws/.lake/packages/{pkg}/.lake/build/lib/lean".format(pkg = pkg))
        if not src.exists:
            continue
        result = rctx.execute(["cp", "-RLn", str(src) + "/.", "lib/"])
        if result.return_code == 0:
            any_merged = True
        else:
            # buildifier: disable=print
            print("rules_lean: WARNING — failed to merge oleans from %s: %s" % (pkg, result.stderr))
    rctx.file("lib/.marker", "")
    return any_merged

def _generate_build_file(rctx, packages_found):
    rctx.file("BUILD.bazel", """\
load("@rules_lean//lean:lean.bzl", "lean_prebuilt_library", "lean_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "lean_bin",
    srcs = ["lean_toolchain/bin/lean"],
)

filegroup(
    name = "runtime",
    srcs = glob(
        [
            "lean_toolchain/bin/**",
            "lean_toolchain/lib/**",
            "lean_toolchain/include/**",
        ],
        allow_empty = True,
    ),
)

lean_toolchain(
    name = "lean_toolchain",
    lean = ":lean_bin",
    runtime = ":runtime",
)

toolchain(
    name = "lean_toolchain_def",
    toolchain = ":lean_toolchain",
    toolchain_type = "@rules_lean//lean:toolchain_type",
)

lean_prebuilt_library(
    name = "Mathlib",
    srcs = glob(["lib/**"], allow_empty = True),
    path_marker = "lib/.marker",
)
""")

def _lake_workspace_impl(rctx):
    platform = _detect_platform(rctx)
    toolchain_content = rctx.read(rctx.path(rctx.attr.lean_toolchain))
    version = _parse_lean_toolchain(toolchain_content)

    _download_lean(rctx, version, platform)
    _stage_lake_workspace(rctx)

    env = _lake_env(rctx)

    # Resolve deps. Lake creates lake-manifest.json if absent, or respects
    # the existing one if revs match. Materializes .lake/packages/<pkg>/.
    update = _run_lake(rctx, ["update"], timeout = 1200, env = env)
    if update.return_code != 0:
        fail("rules_lean: `lake update` failed.\nstdout:\n%s\nstderr:\n%s" %
             (update.stdout, update.stderr))

    # Try the fast path: download prebuilt mathlib oleans from Reservoir.
    cache = _run_lake(rctx, ["exe", "cache", "get"], timeout = 3600, env = env)
    if cache.return_code != 0:
        if rctx.attr.allow_source_build:
            # buildifier: disable=print
            print("rules_lean: `lake exe cache get` failed — falling back to `lake build Mathlib`.")
            build = _run_lake(rctx, ["build", "Mathlib"], timeout = 7200, env = env)
            if build.return_code != 0:
                fail("rules_lean: `lake build Mathlib` failed.\nstdout:\n%s\nstderr:\n%s" %
                     (build.stdout, build.stderr))
        else:
            fail("rules_lean: `lake exe cache get` failed (cache miss or no mathlib in deps).\n" +
                 "Set `allow_source_build = True` to fall back to `lake build` (slow).\n" +
                 "stdout:\n%s\nstderr:\n%s" % (cache.stdout, cache.stderr))

    packages = _list_lake_packages(rctx)
    if not packages:
        fail("rules_lean: no packages found under lake_ws/.lake/packages/ after lake update. " +
             "Is the lakefile missing `require` directives?")

    _consolidate_oleans(rctx, packages)
    _generate_build_file(rctx, packages)

lake_workspace = repository_rule(
    implementation = _lake_workspace_impl,
    attrs = {
        "lean_toolchain": attr.label(
            allow_single_file = True,
            mandatory = True,
            doc = "The `lean-toolchain` file. Drives both Lake's toolchain choice and the Lean binary Bazel downloads.",
        ),
        "lakefile": attr.label(
            allow_single_file = [".lean", ".toml"],
            mandatory = True,
            doc = "The lakefile (deps-only — no library/exe directives for the user's own code).",
        ),
        "lake_manifest": attr.label(
            allow_single_file = [".json"],
            mandatory = True,
            doc = "The committed lake-manifest.json (pins git revs of every Lake dep).",
        ),
        "allow_source_build": attr.bool(
            default = False,
            doc = "If True, fall back to `lake build Mathlib` (~30 min) when `lake exe cache get` fails.",
        ),
    },
    doc = "Materializes a Lake workspace as a Bazel external repo. " +
          "Produces `:lean_toolchain` + `:Mathlib` targets.",
)

def _lake_extension_impl(mctx):
    for mod in mctx.modules:
        for tag in mod.tags.workspace:
            lake_workspace(
                name = tag.name,
                lean_toolchain = tag.lean_toolchain,
                lakefile = tag.lakefile,
                lake_manifest = tag.lake_manifest,
                allow_source_build = tag.allow_source_build,
            )

_workspace_tag = tag_class(attrs = {
    "name": attr.string(mandatory = True),
    "lean_toolchain": attr.label(mandatory = True),
    "lakefile": attr.label(mandatory = True),
    "lake_manifest": attr.label(mandatory = True),
    "allow_source_build": attr.bool(default = False),
})

lake = module_extension(
    implementation = _lake_extension_impl,
    tag_classes = {"workspace": _workspace_tag},
)
